### ISSUE TITLE
Создать TokenManager в auth

### ISSUE THREAD

**Issue by Namxobick** [BitCodersNN/inventory-control.back#16]
Управляет созданием, проверкой и декодированием JWT токенов

**Comment by Stepa123de** [comment]
user_id
role
deadline

**Comment by Stepa123de** [comment]
Создан класс TokenManager для управления токенами
- Реализован класс `TokenManager` в файле [token_manager.py](./src/auth/utils/token_manager.py), который обеспечивает создание, обновление и валидацию токенов доступа и обновления.
- Добавлены методы для генерации токенов и их проверки на действительность.
- Документированы параметры и возвращаемые значения для каждого метода.

Добавлены константы для конфигурации токенов

- Реализована загрузка переменных окружения в файле [token_config.py](./src/configs/token_config.py).
- Определены основные константы, такие как секретный ключ и времена действия токенов доступа и обновления.

Теперь приложение поддерживает полноценное управление токенами безопасности!
