### ISSUE TITLE
Создать AuthService

### ISSUE THREAD

**Issue by Namxobick** [BitCodersNN/inventory-control.back#17]
Обрабатывает бизнес-логику авторизации и аутентификации.

**Comment by Stepa123de** [comment]
# AuthSystem

## `register(user_id, login, password)`
- **Цель:** Регистрация нового пользователя.
- **Результат:**
  - Если имя пользователя уже существует, выбрасывает `Error`.
  - Создает и сохраняет нового пользователя в системе.
- **Параметры:**
  - `login` (str): Уникальное имя пользователя.
  - `password` (str): Пароль пользователя.
  - `user_id` (int): Id пользователя.

---

## `authenticate(login, password)-> Token`
- **Цель:** Аутентификация пользователя.
- **Результат:**
  - Если имя пользователя и пароль верны, возвращает `Token`.
  - Если учетные данные неверны, выбрасывает `login / password incorect`
- **Параметры:**
  - `login` (str): Имя пользователя для аутентификации.
  - `password` (str): Пароль пользователя для проверки.

---

## `logout(user_id)`
- **Цель:** Выход пользователя из системы + обнуление рефрешь токена.
- **Результат:**
  - Если никто не авторизован, выводит сообщение о том, что пользователь не авторизован.
- **Параметры:**
- `user_id` (int): Id пользователя.
---

**Comment by Namxobick** [comment]
Не надо register
Также, наверное, сюда стоит добавить:
  1. abort_all_sessions
  2. create_token
  3. refresh_token

**Comment by Stepa123de** [comment]
create_token
refresh_token
? это не один метод или имеется ввиду создание первого refresh_token?
