### ISSUE TITLE
Поддержка симметричных и асимметричных алгоритмов создания JWT

### ISSUE THREAD

**Issue by Namxobick** [BitCodersNN/inventory-control.back#31]

**Comment by Stepa123de** [comment]
Создание сессий в каждом классе открывает перед нами широкие возможности, но давайте не будем мелочиться. Гораздо целесообразнее использовать одну общую сессию, которая будет управляться через маршруты или центральный API. Это обеспечит независимость модулей и сделает нашу систему более универсальной и гибкой.
